name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release-check:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Test
        run: swift test
      - name: Release build
        run: swift build -c release
